export enum ModemNetworkType {
	'NONE' = 0,
	'GSM' = 1,
	'GPRS' = 2,
	'EDGE' = 3,
	'WCDMA' = 4,
	'WCDMA_HSDPA' = 5,
	'WCDMA_HSUPA' = 6,
	'HSPA' = 7,
	'LTE' = 8,
	'TDS_CDMA' = 9,
	'TDS_HSDPA' = 10,
	'TDS_HSUPA' = 11,
	'TDS_HSPA' = 12,
	'CDMA' = 13,
	'EVDO' = 14,
	'HYBRID' = 15,
	'CDMA_LTE' = 16,
	'eHRPD' = 23,
	'CDMA_eHRPD' = 24
}
